//
// Created by Ted Klein Bergman on 3/15/18.
//

#ifndef OPENGLPROJECT_TEMPORARYTEST_H
#define OPENGLPROJECT_TEMPORARYTEST_H

#define RUN_TEMPORARYTEST false


#endif //OPENGLPROJECT_TEMPORARYTEST_H
